### ISSUE TITLE
Know when cell is pressed?

### ISSUE THREAD

**Issue by dsandmark** [chrisfisher/react-native-directed-scrollview#1]
Hi,

Thanks for creating this component, it's very handy.

Is there a way of knowing when a cell is pressed? I wrap my cells in a `<TouchableOpacity>` but  `onPress` is never called. Do you perhaps consume the onPress event in `ScrollView` or `ScrollViewChild`? Was hoping I could send an `onPress` attribute and have a method called when a cell is pressed.

```javascript
class GridContent extends Component {
...
renderCell(cell) {
  return (
    <TouchableOpacity
      onPress = {() => { console.log('onPress') }}
      key = {cell.id}
      style = {styles.cellContainer}
    >
      <Text>{cell.id}</Text>
    </TouchableOpacity>
  )
}
...
```

Thank you.

**Comment by dsandmark** [comment]
@chrisfisher

**Comment by chrisfisher** [comment]
@dsandmark I'm currently working on a fix for this, it should be ready to land within the next few days.

**Comment by chrisfisher** [comment]
@dsandmark I've made a minor change, updated the example and published a new patch version. You can control which views should intercept touch events by using the `pointerEvents` prop. I can't get it to work as well in Android, but as the example shows you can work around this somewhat.

**Comment by dsandmark** [comment]
Thank you @chrisfisher, will have a look. Our main platform is Android but anything that works will do for now.

**Comment by dsandmark** [comment]
Works like a charm. Thank you @chrisfisher.
