### ISSUE TITLE
Parameter for adjusting scroll start?

### ISSUE THREAD

**Issue by bitfabrikken** [chrisfisher/react-native-directed-scrollview#10]
Thanks for a great module :)

Right now, the scrollview immediately scrolls on touch, thus "stealing" the touch event for the any buttons/Touchable components that might be in it.

Would it be possible to add a sort of minimum touch movement before the scroll happens? As it is now, when I try to click on a button, I have to be extremely careful not to move my finger, otherwise the button doesn't receive the event.

**Comment by cinan** [comment]
this makes the scrollview pretty unusable on android

**Comment by chrisfisher** [comment]
Fixed by https://github.com/chrisfisher/react-native-directed-scrollview/pull/18/files
