### ISSUE TITLE
onScroll and other callbacks are not called

### ISSUE THREAD

**Issue by MichaelDanielTom** [chrisfisher/react-native-directed-scrollview#15]
Hey guys,
I'm having trouble getting some of the scrollview callbacks to trigger like onMomentumScrollEnd and onScroll. These callbacks do not seem to be called on the underlying NativeScrollView component either. Anyone have any idea what's going on? I'm using RN-0.48.0 on iOS 11. 

Thanks for making this great component!

**Comment by MichaelDanielTom** [comment]
Fixed it with this pull request https://github.com/chrisfisher/react-native-directed-scrollview/pull/16

**Comment by chrisfisher** [comment]
Merged #16 and published `v3.0.1`
