### ISSUE TITLE
How to use with expo.io?

### ISSUE THREAD

**Issue by faria** [chrisfisher/react-native-directed-scrollview#17]
I used exp init to create a new project.  I did npm install --save of this library.  In App.js I import ScrollView and ScrollViewChild. I use exp start to run the App, and the Expo client on my phone to view it.  
I get the error: 
Warning: Native component for "DirectedScrollView" does not exist
and similar error for ScrollViewChild.
How can I resolve this? 
Thanks.

**Comment by chrisfisher** [comment]
This module contains custom native code so isn't compatible with expo unfortunately.
