### ISSUE TITLE
Zoom event

### ISSUE THREAD

**Issue by lecler-i** [chrisfisher/react-native-directed-scrollview#20]
Hello !

First, thanks for all the work, this little lib of yours is awesome !
It fits perfectly my needs, i just have one or two little features missing and it would be awesome... I don't know if you want to give it a look ?

#### onZoom event

Give a `onZoom` callback on props, that will be called on zoom with the actual scalefactor.
That would be pretty awesome to... add details to the grid the more we zoom in for example.

#### DirectedScrollViewChild : `disableZoom` props

Simple and straightForward... be able to not apply the zoon on a `DirectedScrollViewChild` (in case of the fix header for example)

I know, i can't really ask you to add features like that... I tried myself and i know only a bit about java and i didnt even manage to get anything working... (not even speaking about android)

I know it should not be that hard to implement too, so if someone have a little bit of spare time... would really appreciate <3

**Comment by lecler-i** [comment]
Ill try to make those work and submit a PR but it would be only for android, as i don't have any Apple device...

**Comment by chrisfisher** [comment]
Happy to review/merge any PRs you want to make. I don't have much time to spend on adding new features currently I'm afraid. The onZoom event should be easy to add for iOS so I can do that if you want to submit a PR for Android only.
