### ISSUE TITLE
Getting com.facebook.react.bridge.NativeArgumentsParseException

### ISSUE THREAD

**Issue by kkarmalkar** [chrisfisher/react-native-directed-scrollview#31]
I have used scrollview given in sample app and when I run it on android it throwing below error:

`com.facebook.react.bridge.NativeArgumentsParseException: TypeError: expected dynamic type `double', but had type `null' (constructing arguments for UIManager.dispatchViewManagerCommand at argument index 1)`

"react": "^16.2.0",
"react-native": "^0.49.5",
"react-native-directed-scrollview": "^1.3.6",

Can anyone help me out.. please.!!

**Comment by lecler-i** [comment]
This is related to commit 767081ef8c242e30b08abe703d98deafc9e548f1

https://github.com/chrisfisher/react-native-directed-scrollview/commit/767081ef8c242e30b08abe703d98deafc9e548f1#diff-168726dbe96b3ce427e7fedce31bb0bc

That fix a bug on iOS for a regression on Android.
I'll try to send a PR tomorrow to fix the issue

**Comment by kkarmalkar** [comment]
Thanks @lecler-i ... let me know once issue is fixed and in which version it is fixed?

**Comment by kkarmalkar** [comment]
Hi @lecler-i, it will really helpful if this issue gets fixed as earliest, one of our app is going live on production and before that we want to fix issue observed. We appreciate your help.. Thanks..!!

**Comment by SatVel** [comment]
@lecler-i - I am also facing this issue. It would be great if you could give a bug-fix ASAP. Thanking you in advance!

**Comment by ChengHsuanLiu** [comment]
@kkarmalkar This issue happened to me too. My app works well on iOS but when I run on Android, it shows type error as below:

![29132993_10204634004805715_5150280560932814848_o](https://user-images.githubusercontent.com/10514885/37293037-29ce122a-264d-11e8-84f8-d44e15d83c29.png)

Any solutions here?

**Comment by kkarmalkar** [comment]
@ChengHsuanLiu I am still waiting for solution from @lecler-i , he is going to fix it

**Comment by lecler-i** [comment]
Hello,


Sorry i won't have the time right now, busy week...

Don't count on me for this, i will but when i find time to

Best is to revert on previous version that should be usable and without 
the issue

**Comment by lecler-i** [comment]
Clean fix by @kevinsperrine

https://github.com/kevinsperrine/react-native-directed-scrollview/commit/87c2583dd13f94427672b3a82dac5d761e025169

**Comment by chrisfisher** [comment]
Try `1.3.7` for @kevinsperrine's fix.
