### ISSUE TITLE
Android - Type Error. Error happened once ScrollView rendered

### ISSUE THREAD

**Issue by ChengHsuanLiu** [chrisfisher/react-native-directed-scrollview#32]
Versions:
"react-native": "0.53.3"
"react": "16.2.0"
"react-native-directed-scrollview": "1.3.6"

Code:
![2018-03-12 11 20 36](https://user-images.githubusercontent.com/10514885/37292556-0c291dc4-264c-11e8-8042-dec92733585a.png)

Works Perfect on iOS but shows type error on android:
`TypeError: expected dynamic type double, but had type null constructing arguments for UiManager.dispatchViewManagerCommand at argument index 1`

![29132993_10204634004805715_5150280560932814848_o](https://user-images.githubusercontent.com/10514885/37292629-36e670f2-264c-11e8-948d-d6b4c028dff9.png)

Please help me :(

**Comment by chrisfisher** [comment]
Should be fixed with `1.3.7`
