### ISSUE TITLE
TouchableHighlight's onPress overly sensitive within a ScrollViewChild (android) 

### ISSUE THREAD

**Issue by coderdave** [chrisfisher/react-native-directed-scrollview#4]
I noticed that the `onPress` for`TouchableHighlight` is overly sensitive within a `ScrollViewChild` as I scroll around the content view area.

If the `TouchableHighlight` is within a regular react-native `ScrollView`, it's not sensitive like this.

In the documentation for `onPress` (https://facebook.github.io/react-native/docs/touchablewithoutfeedback.html#onpress) it says that it's "Called when the touch is released, but not if cancelled (e.g. by a scroll that steals the responder lock)."

Is it maybe not being cancelled properly because it's within a `ScrollViewChild`?

**Comment by chrisfisher** [comment]
@coderdave I've just released an update in v1.1.4 which fixes this. Try it out and let me know.

**Comment by coderdave** [comment]
Thanks for working on a fix so quickly! However, it still seems too sensitive. Notice the gif below where the time slots have the onPress event.

![scrolling](https://cloud.githubusercontent.com/assets/964751/24549723/b0ca221c-15e8-11e7-9864-8f12df14fa21.gif)

**Comment by chrisfisher** [comment]
@coderdave Is that example in the gif running on iOS or Android? It looks iOS-ish, but the issue title says Android - just want to confirm.

**Comment by coderdave** [comment]
Yes it's android.

**Comment by chrisfisher** [comment]
@coderdave My bad, I thought I'd fixed it in Android but looks like I hadn't. I've now pushed another update in **1.1.5** which fixes it properly. It still needs fixing in iOS - I'll try get that done soon.

**Comment by coderdave** [comment]
@chrisfisher It works pretty good now. As a side effect, it doesn't show the underlay color when I tap the time slots (TouchableHighligh) unless I keep my finger there for a second, but that could be do to my implementation, not necessarily to this library.

**Comment by YatsukBogdan1** [comment]
@chrisfisher do you have time to fix this issue on iOS? cause touchables still very sensitive. this component is really useful for my project and i need it. i will appreciate some help, at least some ideas how i can fix this in native code for iOS by myself.
