### ISSUE TITLE
Not work on android

### ISSUE THREAD

**Issue by jiangbophd** [chrisfisher/react-native-directed-scrollview#6]
Dear,

I test your examples, it is not work on android.

Could you tell me how to resolve it?

Thanks

**Comment by chrisfisher** [comment]
@jiangbophd Can you provide more detail on the error you're getting? A screenshot or a stack trace would be helpful.

**Comment by jiangbophd** [comment]
@chrisfisher  Thanks for you reply, I test your example, it is can not scroll in android. I do not know why.

**Comment by chrisfisher** [comment]
@jiangbophd What model / version of Android are you running? Emulator or device?

**Comment by heliosPortal** [comment]
@chrisfisher I am having the same issue with android.  It is related to the version of RN.  When I run the example app unchanged, it works great.  But when I upgrade RN to the latest (43.4) the scrolling does not work.  The app comes up fine and displays the grid, but no scrolling.  FWIW, the click event on the cells works fine. There are no errors in the javascript console.  I am running in Genymotion 2.9.0 with galaxy s7, api 25.  I was having the same problem, though, with an s6 image with version 23.  I'd love to be able to help, but have not jumped into android native development, yet... 
Thanks!

**Comment by chrisfisher** [comment]
@heliosPortal Thanks for the detail. I found the issue - it was due to the following change in 0.43.4: https://github.com/facebook/react-native/commit/88eeea0995faa800e3b9e48461f95488c73f7fd9. I've published a fix in version 1.2.0.

**Comment by m-tbox** [comment]
@chrisfisher does this library support 0.20.0 or 0.24.1 ?
can you please tell what is the minimum version supported ?

**Comment by chrisfisher** [comment]
No, unfortunately not. The minimum version is specified in `package.json` under `peerDependencies` - it's now `0.43.4`.
