### ISSUE TITLE
Zoom gesture doesn't zoom where you pinch

### ISSUE THREAD

**Issue by bitfabrikken** [chrisfisher/react-native-directed-scrollview#9]
Seems the zoom is applied to 0,0 xy and not the place you zoom. 
So for instance zooming in on a specific spot on a photo isn't possible.

**Comment by luisfuertes** [comment]
+1, cant see mi right and bottom elements because zoom is in 0,0.

**Comment by chrisfisher** [comment]
@bitfabrikken I've published `1.2.1` with a fix for not zooming around the pinch position in Android. Closing this issue for now.
